site_name: envswitch
# site_description: 'A short description of my project'
repo_url: https://github.com/smarie/env-switcher-gui
pages:
    - Home: index.md
    #- Usage details: usage.md
    - Changelog: changelog.md
theme: material  # readthedocs  mkdocs

markdown_extensions:
  - admonition  # to add notes such as http://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - codehilite(guess_lang=false)
  - toc(permalink=true)