# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sprint1_hardcoded.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.envsTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.envsTabWidget.setObjectName("envsTabWidget")
        self.env1 = QtWidgets.QWidget()
        self.env1.setObjectName("env1")
        self.formLayoutWidget = QtWidgets.QWidget(self.env1)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 751, 451))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.var1Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.var1Label.setObjectName("var1Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.var1Label)
        self.var1LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.var1LineEdit.setObjectName("var1LineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.var1LineEdit)
        self.var2Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.var2Label.setObjectName("var2Label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.var2Label)
        self.var2LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.var2LineEdit.setObjectName("var2LineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.var2LineEdit)
        self.var3Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.var3Label.setObjectName("var3Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.var3Label)
        self.var3LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.var3LineEdit.setObjectName("var3LineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.var3LineEdit)
        self.var4Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.var4Label.setObjectName("var4Label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.var4Label)
        self.var4LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.var4LineEdit.setObjectName("var4LineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.var4LineEdit)
        self.envsTabWidget.addTab(self.env1, "")
        self.env2 = QtWidgets.QWidget()
        self.env2.setObjectName("env2")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.env2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 751, 451))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.var1Label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.var1Label_3.setObjectName("var1Label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.var1Label_3)
        self.var1LineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.var1LineEdit_3.setObjectName("var1LineEdit_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.var1LineEdit_3)
        self.var2Label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.var2Label_3.setObjectName("var2Label_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.var2Label_3)
        self.var2LineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.var2LineEdit_3.setObjectName("var2LineEdit_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.var2LineEdit_3)
        self.var3Label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.var3Label_3.setObjectName("var3Label_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.var3Label_3)
        self.var3LineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.var3LineEdit_3.setText("")
        self.var3LineEdit_3.setObjectName("var3LineEdit_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.var3LineEdit_3)
        self.var4Label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.var4Label_3.setObjectName("var4Label_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.var4Label_3)
        self.var4LineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.var4LineEdit_3.setText("")
        self.var4LineEdit_3.setObjectName("var4LineEdit_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.var4LineEdit_3)
        self.envsTabWidget.addTab(self.env2, "")
        self.verticalLayout.addWidget(self.envsTabWidget)
        self.okCancelApplyButtonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.okCancelApplyButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.okCancelApplyButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.okCancelApplyButtonBox.setObjectName("okCancelApplyButtonBox")
        self.verticalLayout.addWidget(self.okCancelApplyButtonBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_Environment = QtWidgets.QAction(MainWindow)
        self.actionAdd_Environment.setObjectName("actionAdd_Environment")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad_configuration = QtWidgets.QAction(MainWindow)
        self.actionLoad_configuration.setObjectName("actionLoad_configuration")
        self.actionSave_configuration = QtWidgets.QAction(MainWindow)
        self.actionSave_configuration.setObjectName("actionSave_configuration")
        self.actionLoad_configuration_2 = QtWidgets.QAction(MainWindow)
        self.actionLoad_configuration_2.setObjectName("actionLoad_configuration_2")
        self.actionSave_configuration_As = QtWidgets.QAction(MainWindow)
        self.actionSave_configuration_As.setObjectName("actionSave_configuration_As")
        self.menuFile.addAction(self.actionLoad_configuration_2)
        self.menuFile.addAction(self.actionSave_configuration_As)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.envsTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.var1Label.setText(_translate("MainWindow", "http_proxy"))
        self.var2Label.setText(_translate("MainWindow", "https_proxy"))
        self.var3Label.setText(_translate("MainWindow", "no_proxy"))
        self.var4Label.setText(_translate("MainWindow", "curl_ca_bundle"))
        self.envsTabWidget.setTabText(self.envsTabWidget.indexOf(self.env1), _translate("MainWindow", "No Proxy"))
        self.var1Label_3.setText(_translate("MainWindow", "http_proxy"))
        self.var1LineEdit_3.setText(_translate("MainWindow", "http://localhost:8080"))
        self.var2Label_3.setText(_translate("MainWindow", "https_proxy"))
        self.var2LineEdit_3.setText(_translate("MainWindow", "http://localhost:4443"))
        self.var3Label_3.setText(_translate("MainWindow", "no_proxy"))
        self.var4Label_3.setText(_translate("MainWindow", "curl_ca_bundle"))
        self.envsTabWidget.setTabText(self.envsTabWidget.indexOf(self.env2), _translate("MainWindow", "Proxy"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAdd_Environment.setText(_translate("MainWindow", "Load..."))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.actionLoad_configuration.setText(_translate("MainWindow", "Load"))
        self.actionSave_configuration.setText(_translate("MainWindow", "Save"))
        self.actionLoad_configuration_2.setText(_translate("MainWindow", "Load configuration"))
        self.actionSave_configuration_As.setText(_translate("MainWindow", "Save configuration As..."))

